// AUTO-GENERATED by tools/docs-gen — do not edit.
// Source: docs/en/*.md and docs/ru/*.md. Run `npm run docs:gen` to regenerate.
import type { DocArticle } from './docs-content';

export const DOC_ARTICLES: DocArticle[] = [
  {
    "slug": "welcome",
    "title": {
      "en": "Welcome",
      "ru": "Добро пожаловать"
    },
    "summary": {
      "en": "What TrackLab is and where to start.",
      "ru": "Что такое TrackLab и с чего начать."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "Welcome to TrackLab, your tracking assistant. With it you can:",
          "ru": "Добро пожаловать в TrackLab, ваш ассистент по трекингу. С ним вы можете:"
        }
      },
      {
        "t": "ol",
        "items": [
          {
            "en": "Track your activity with custom metrics and lists ([read more](./activities.md)).",
            "ru": "Отслеживать свою активность с помощью своих метрик и списков ([подробнее](./activities.md))."
          },
          {
            "en": "Set up rules to build your routine and achieve your goals ([read more](./rules.md)).",
            "ru": "Настраивать правила, чтобы выстроить рутину и достигать целей ([подробнее](./rules.md))."
          },
          {
            "en": "Conduct experiments to understand what works personally for you ([read more](./experiments.md)).",
            "ru": "Проводить эксперименты, чтобы понять, что работает именно для вас ([подробнее](./experiments.md))."
          }
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "Read [Getting Started](./getting-started.md) to make your first steps and understand basic mechanics.",
          "ru": "Прочитайте [Начало работы](./getting-started.md), чтобы сделать первые шаги и разобраться в базовых механиках."
        }
      },
      {
        "t": "p",
        "text": {
          "en": "If you have any questions, please check the documentation, or contact [tracklab@etsbox.com](mailto:tracklab@etsbox.com).",
          "ru": "Если у вас есть вопросы, загляните в документацию или напишите на [tracklab@etsbox.com](mailto:tracklab@etsbox.com)."
        }
      }
    ]
  },
  {
    "slug": "getting-started",
    "title": {
      "en": "Getting Started",
      "ru": "Начало работы"
    },
    "summary": {
      "en": "The first few minutes with TrackLab.",
      "ru": "Первые несколько минут с TrackLab."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "This page walks you through your first few minutes with TrackLab.",
          "ru": "Эта страница проведёт вас через первые несколько минут работы с TrackLab."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "1. Log an activity",
          "ru": "1. Запишите активность"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "You can start an activity three ways:",
          "ru": "Начать активность можно тремя способами:"
        }
      },
      {
        "t": "ul",
        "items": [
          {
            "en": "press \"add\" at the bottom of the history page",
            "ru": "нажать «добавить» внизу страницы истории"
          },
          {
            "en": "press an action button on the [dashboard](./dashboard.md)",
            "ru": "нажать кнопку действия на [панели](./dashboard.md)"
          },
          {
            "en": "follow [this link](/activity/add)",
            "ru": "перейти по [этой ссылке](/activity/add)"
          }
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "In the form, enter one or more actions (for example \"Running\"), set the date and time, and save. That is enough for a minimal activity.",
          "ru": "В форме введите одно или несколько действий (например, «Бег»), укажите дату и время и сохраните. Этого достаточно для минимальной активности."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "2. Track more than time",
          "ru": "2. Отслеживайте больше, чем время"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "For richer tracking, add two kinds of detail to an activity:",
          "ru": "Для более детального трекинга добавляйте в активность два вида данных:"
        }
      },
      {
        "t": "ul",
        "items": [
          {
            "en": "[Metrics](./metrics.md) — number values, like Mood, Energy or Weight.",
            "ru": "[Метрики](./metrics.md) — числовые значения, например Настроение, Энергия или Вес."
          },
          {
            "en": "[Library](./library.md) — your collection of lists, each holding items: food, places, people, purchases, projects, and so on.",
            "ru": "[Библиотека](./library.md) — ваша коллекция списков, каждый со своими элементами: еда, места, люди, покупки, проекты и так далее."
          }
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "Right in the activity form you can create a new metric or list on the spot, and it is saved for next time.",
          "ru": "Прямо в форме активности можно создать новую метрику или список на месте, и они сохранятся на будущее."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "3. Look at the numbers",
          "ru": "3. Посмотрите на цифры"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "After creating several activities, you can see statistics. Statistics show how much time you spent on an action or list item, as well as how a metric's value changes over a period of time, with a calculated average.",
          "ru": "Создав несколько активностей, вы сможете видеть статистику по ним. Статистика показывает, сколько времени вы потратили на действие или элемент списка, а также как значение метрики меняется за период времени, с рассчитанным средним значением."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "4. Go further",
          "ru": "4. Идите дальше"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Turn a habit into a commitment with [rules](./rules.md) — checks like \"run at least 3 times a week\" that show up on your dashboard. When you want to test whether a change actually helps, run an [experiment](./experiments.md): it ties metrics, lists and rules together to answer \"did this change anything?\".",
          "ru": "Превратите привычку в обязательство с помощью [правил](./rules.md) — проверок вроде «бегать не менее 3 раз в неделю», которые появляются на панели. А когда захотите проверить, действительно ли изменение помогает, проведите [эксперимент](./experiments.md): он связывает метрики, списки и правила, чтобы ответить на вопрос «изменило ли это что-нибудь?»."
        }
      }
    ]
  },
  {
    "slug": "activities",
    "title": {
      "en": "Activities",
      "ru": "Активности"
    },
    "summary": {
      "en": "The main tracking unit, and how the add form fills itself in.",
      "ru": "Основная единица трекинга и как форма добавления заполняется сама."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "An activity is the main tracking unit that has a date, start time, end time, actions, tags, custom lists and metrics.",
          "ru": "Активность — основная единица трекинга, у которой есть дата, время начала, время окончания, действия, теги, свои списки и метрики."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Time",
          "ru": "Время"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "An activity covers a fixed block of time from start to end. All of its actions are considered performed during that block. If you \"worked, listened to music\" from 12:00 to 15:00, you worked for three hours and listened to music for three hours.",
          "ru": "Активность занимает фиксированный отрезок времени от начала до конца. Все её действия считаются выполненными в течение этого отрезка. Если вы «работали, слушали музыку» с 12:00 до 15:00, значит вы работали три часа и слушали музыку три часа."
        }
      },
      {
        "t": "p",
        "text": {
          "en": "One day lasts from 00:00 to 23:59. If an activity crosses midnight (for example starts at 23:50 and ends at 00:10), it counts as the last activity of the previous day.",
          "ru": "Один день длится с 00:00 до 23:59. Если активность пересекает полночь (например, начинается в 23:50 и заканчивается в 00:10), она считается последней активностью предыдущего дня."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Adding an activity",
          "ru": "Добавление активности"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Press \"add\" button on the bottom of the history page or an action button on the dashboard.",
          "ru": "Нажмите кнопку «добавить» внизу страницы истории или кнопку действия на панели."
        }
      }
    ]
  },
  {
    "slug": "metrics",
    "title": {
      "en": "Metrics",
      "ru": "Метрики"
    },
    "summary": {
      "en": "Numbers you attach to activities, and when they count.",
      "ru": "Числа, которые вы привязываете к активностям, и когда они учитываются."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "A metric is a number you record on an activity — Mood, Energy, Weight. TrackLab ships a few; add your own in Lab.",
          "ru": "Метрика — число, которое вы записываете в активности: Настроение, Энергия, Вес. В приложении уже есть несколько; свои добавляйте в «Лаборатории»."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "When a value counts",
          "ru": "Когда значение учитывается"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "A metric value is treated as the state at the activity's end time, not its start. You log activities after they happen, so the value reflects the moment the activity finished. Graphs plot each value at that end time.",
          "ru": "Значение метрики считается состоянием на время окончания активности, а не начала. Вы записываете активности после того, как они произошли, поэтому значение отражает момент, когда активность завершилась. Графики ставят каждое значение на это время окончания."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Shape of a metric",
          "ru": "Из чего состоит метрика"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Each metric has a step and an optional range (min and max) that bound what you can enter, plus an optional unit shown next to the value. Turn on \"show previous value\" to see your last entry as a hint while logging.",
          "ru": "У каждой метрики есть шаг и необязательный диапазон (минимум и максимум), которые ограничивают вводимое значение, а также необязательная единица, показываемая рядом со значением. Включите «показывать предыдущее значение», чтобы во время записи видеть прошлую запись как подсказку."
        }
      }
    ]
  },
  {
    "slug": "library",
    "title": {
      "en": "Library",
      "ru": "Библиотека"
    },
    "summary": {
      "en": "Where your lists and their items live.",
      "ru": "Где живут ваши списки и их элементы."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "The library is where your lists live. A list is your own set of items you can attach to an activity — for example, a list named \"Emotions\" holds items like \"angry, happy, calm\". Create lists and items in Lab.",
          "ru": "Библиотека — место, где живут ваши списки. Список — ваш собственный набор элементов, которые можно привязать к активности: например, список «Эмоции» содержит элементы вроде «злой, счастливый, спокойный». Создавайте списки и элементы в «Лаборатории»."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "When items appear",
          "ru": "Когда появляются элементы"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "A list's items show up in the activity form when you select an action or tag linked to that list. A list linked to nothing is always available. This keeps the form short — you only see the vocabulary that fits what you did.",
          "ru": "Элементы списка появляются в форме активности, когда вы выбираете связанное с ним действие или тег. Список, не связанный ни с чем, доступен всегда. Так форма остаётся короткой — вы видите только тот словарь, который подходит к тому, что вы делали."
        }
      }
    ]
  },
  {
    "slug": "rules",
    "title": {
      "en": "Rules",
      "ru": "Правила"
    },
    "summary": {
      "en": "Commitments you check yourself against, on the dashboard and in experiments.",
      "ru": "Обязательства, которые вы проверяете, — на панели и в экспериментах."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "A rule is a commitment you can hold yourself to, for example \"run at least 3 times a week\". Rules show up on the dashboard as a checklist and can drive experiments.",
          "ru": "Правило — обязательство, которого вы держитесь, например «бегать не менее 3 раз в неделю». Правила появляются на панели в виде чек-листа и могут управлять экспериментами."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "How a rule is built",
          "ru": "Из чего состоит правило"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Pick a subject — an action, tag or list item — then what to measure about it:",
          "ru": "Выберите предмет — действие, тег или элемент списка — затем что о нём измерять:"
        }
      },
      {
        "t": "ul",
        "items": [
          {
            "en": "number of times it happened,",
            "ru": "сколько раз оно случилось,"
          },
          {
            "en": "total time spent on it, or",
            "ru": "сколько времени на него ушло, или"
          },
          {
            "en": "number of days it happened.",
            "ru": "в скольких днях оно случилось."
          }
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "Add a target with ≥ or ≤ and a period: day, week or month. Optional start and end dates limit when the rule runs; an optional time window limits which activities count toward it.",
          "ru": "Задайте цель со знаком ≥ или ≤ и период: день, неделя или месяц. Необязательные даты начала и конца ограничивают, когда правило действует; необязательное временное окно ограничивает, какие активности идут в зачёт."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Checking",
          "ru": "Проверка"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "TrackLab evaluates the rule once per period and marks it met or missed. Inside an experiment, your share of met checks — the uptime — is one of the things that decides whether the experiment succeeds.",
          "ru": "TrackLab оценивает правило один раз за период и отмечает его выполненным или нет. Внутри эксперимента доля выполненных проверок — дисциплина — одна из вещей, определяющих, удался ли эксперимент."
        }
      }
    ]
  },
  {
    "slug": "experiments",
    "title": {
      "en": "Experiments",
      "ru": "Эксперименты"
    },
    "summary": {
      "en": "Test whether a change did anything, with indicators and rules.",
      "ru": "Проверьте, изменило ли что-то ваше решение, — индикаторы и правила."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "An experiment answers one question: did this change anything? You name a period, say what you want to watch, and optionally promise what you will do during it. TrackLab then compares what happened against the week before the experiment started.",
          "ru": "Эксперимент отвечает на один вопрос: изменило ли это что-нибудь? Вы задаёте период, указываете, за чем хотите следить, и по желанию обещаете, что будете делать. Затем TrackLab сравнивает произошедшее с неделей до начала эксперимента."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Indicators — what is measured",
          "ru": "Индикаторы — что измеряется"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "An indicator is any entity you already track: a metric (Mood), an action (Running), a tag, or a list item. Each indicator carries a direction:",
          "ru": "Индикатор — любая сущность, которую вы уже отслеживаете: метрика (Настроение), действие (Бег), тег или элемент списка. У каждого индикатора есть направление:"
        }
      },
      {
        "t": "table",
        "headers": [
          {
            "en": "Direction",
            "ru": "Направление"
          },
          {
            "en": "Meaning",
            "ru": "Значение"
          }
        ],
        "rows": [
          [
            {
              "en": "Up",
              "ru": "Вверх"
            },
            {
              "en": "You expect this to grow",
              "ru": "Вы ожидаете рост"
            }
          ],
          [
            {
              "en": "Down",
              "ru": "Вниз"
            },
            {
              "en": "You expect this to shrink",
              "ru": "Вы ожидаете снижение"
            }
          ],
          [
            {
              "en": "Any",
              "ru": "Любое"
            },
            {
              "en": "You only watch it, it cannot fail",
              "ru": "Только наблюдаете, провалиться не может"
            }
          ]
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "For metrics, the value is the average of the values you logged. For actions, tags and items, it is the total time spent. An experiment can hold up to three indicators.",
          "ru": "Для метрик значение — среднее из записанных вами значений. Для действий, тегов и элементов — суммарное затраченное время. Эксперимент может содержать до трёх индикаторов."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Rules — what you promise",
          "ru": "Правила — что вы обещаете"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "A rule is a commitment for the duration, for example \"Running at least 3 times a week\". Rules are checked per day, week or month and appear on your dashboard as a checklist. Rules are optional — add them when the experiment is about changing a habit rather than just observing one. An experiment can hold up to three rules.",
          "ru": "Правило — обязательство на весь период, например «Бегать не менее 3 раз в неделю». Правила проверяются по дням, неделям или месяцам и появляются на панели в виде чек-листа. Правила необязательны — добавляйте их, когда эксперимент о смене привычки, а не просто о наблюдении. Эксперимент может содержать до трёх правил."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "The baseline",
          "ru": "Базовая линия"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "The starting value of each indicator is taken from the seven days before the start date. The form shows it as soon as you pick an indicator and a period. If there is no data in that week, TrackLab says so and uses the experiment's first week as the baseline instead.",
          "ru": "Начальное значение каждого индикатора берётся из семи дней перед датой старта. Форма показывает его, как только вы выберете индикатор и период. Если данных за ту неделю нет, TrackLab сообщит об этом и вместо неё возьмёт за базу первую неделю эксперимента."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Creating one",
          "ru": "Создание"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Open Lab → Experiments → +. Fill in:",
          "ru": "Откройте Лаборатория → Эксперименты → +. Заполните:"
        }
      },
      {
        "t": "ol",
        "items": [
          {
            "en": "Title — what you are testing, for example \"Morning runs\".",
            "ru": "Название — что вы проверяете, например «Утренние пробежки»."
          },
          {
            "en": "Period — start and end date. Defaults to one month.",
            "ru": "Период — даты начала и конца. По умолчанию один месяц."
          },
          {
            "en": "Indicators — press \"Add\" and pick from the list.",
            "ru": "Индикаторы — нажмите «Добавить» и выберите из списка."
          },
          {
            "en": "Rules — press \"Add\" and pick from the list.",
            "ru": "Правила — нажмите «Добавить» и выберите из списка."
          }
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "If a picker is empty, or what you need is not in it, use the New metric / New action / New tag / New item / New rule buttons pinned at the bottom of the picker. They open the same form the dedicated pages use, save it, and select the result for you — you never leave the experiment. This nests: creating a rule here lets you create its subject action the same way.",
          "ru": "Если список выбора пуст или в нём нет нужного, используйте кнопки «Новая метрика / Новое действие / Новый тег / Новый элемент / Новое правило», закреплённые внизу списка. Они открывают ту же форму, что и отдельные страницы, сохраняют её и сразу подставляют результат — вы не покидаете эксперимент. Это вложено: создавая здесь правило, можно так же создать и действие для него."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "How it finishes",
          "ru": "Как завершается"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "An experiment runs until its end date, then TrackLab marks it Success or Failed. It can also fail early:",
          "ru": "Эксперимент идёт до даты окончания, затем TrackLab отмечает его как Успех или Провал. Он может провалиться и раньше:"
        }
      },
      {
        "t": "table",
        "headers": [
          {
            "en": "Outcome",
            "ru": "Итог"
          },
          {
            "en": "When",
            "ru": "Когда"
          }
        ],
        "rows": [
          [
            {
              "en": "Success",
              "ru": "Успех"
            },
            {
              "en": "The end date passed and every up/down indicator moved as expected",
              "ru": "Дата окончания прошла, и каждый индикатор вверх/вниз изменился как ожидалось"
            }
          ],
          [
            {
              "en": "Failed — trend not met",
              "ru": "Провал — тренд не достигнут"
            },
            {
              "en": "The end date passed and an indicator moved the wrong way",
              "ru": "Дата окончания прошла, а индикатор изменился не туда"
            }
          ],
          [
            {
              "en": "Failed — low uptime",
              "ru": "Провал — низкая дисциплина"
            },
            {
              "en": "After the first week, fewer than 50% of your rule checks were met",
              "ru": "После первой недели выполнено менее 50% проверок правил"
            }
          ],
          [
            {
              "en": "Failed — initial values not logged",
              "ru": "Провал — нет начальных значений"
            },
            {
              "en": "After the first week, a trending metric still has no value to compare against",
              "ru": "После первой недели у трендовой метрики так и нет значения для сравнения"
            }
          ],
          [
            {
              "en": "Failed — final values not logged",
              "ru": "Провал — нет итоговых значений"
            },
            {
              "en": "The experiment ended with no data to compare against",
              "ru": "Эксперимент закончился без данных для сравнения"
            }
          ]
        ]
      },
      {
        "t": "p",
        "text": {
          "en": "Indicators set to \"any\" never cause a failure. Uptime only applies when the experiment has rules — an observation-only experiment cannot fail on uptime.",
          "ru": "Индикаторы со значением «любое» никогда не приводят к провалу. Дисциплина учитывается только если у эксперимента есть правила — эксперимент лишь для наблюдения не может провалиться по дисциплине."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "While it runs",
          "ru": "Пока он идёт"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Keep logging activities as usual. That is the only input an experiment needs; it reads the same records the rest of the app does. The dashboard shows the rule checklist for the current period, so the daily loop stays the same as any other day.",
          "ru": "Продолжайте записывать активности как обычно. Это единственный ввод, который нужен эксперименту; он читает те же записи, что и остальное приложение. Панель показывает чек-лист правил для текущего периода, так что ежедневный цикл не меняется."
        }
      }
    ]
  },
  {
    "slug": "statistics",
    "title": {
      "en": "Statistics",
      "ru": "Статистика"
    },
    "summary": {
      "en": "Your activities as graphs — what they show and how time is read.",
      "ru": "Ваши активности в виде графиков — что показывают и как читается время."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "Stats turn your activities into graphs. Nothing appears until there is data — one activity is enough for the first point.",
          "ru": "«Статистика» превращает ваши активности в графики. Пока нет данных, ничего не показывается — одной активности достаточно для первой точки."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "What you can see",
          "ru": "Что можно увидеть"
        }
      },
      {
        "t": "ul",
        "items": [
          {
            "en": "How a metric moves over time — up to three at once, to compare them.",
            "ru": "Как метрика меняется со временем — до трёх сразу, чтобы сравнивать."
          },
          {
            "en": "How much time went to a specific action, tag or list item.",
            "ru": "Сколько времени ушло на конкретное действие, тег или элемент списка."
          }
        ]
      },
      {
        "t": "h",
        "text": {
          "en": "Time reference",
          "ru": "Отсчёт времени"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Metric graphs place each value at the activity's end time and interpolate between points, so the line reflects when things actually changed. Pick a date range at the top to focus any graph on a period.",
          "ru": "Графики метрик ставят каждое значение на время окончания активности и соединяют точки интерполяцией, поэтому линия отражает, когда всё действительно менялось. Выберите диапазон дат сверху, чтобы сфокусировать любой график на периоде."
        }
      }
    ]
  },
  {
    "slug": "dashboard",
    "title": {
      "en": "Dashboard",
      "ru": "Панель"
    },
    "summary": {
      "en": "The home screen — a grid of widgets you arrange yourself.",
      "ru": "Главный экран — сетка виджетов, которую вы настраиваете сами."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "The dashboard is the home screen: a grid of widgets you arrange in Dashboard settings. Each widget resizes to its cell, so the layout fits any screen.",
          "ru": "Панель — главный экран: сетка виджетов, которую вы собираете в настройках панели. Каждый виджет подстраивается под свою ячейку, поэтому раскладка подходит под любой экран."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Widgets",
          "ru": "Виджеты"
        }
      },
      {
        "t": "ul",
        "items": [
          {
            "en": "Quick add — one tap to start a new activity or tag.",
            "ru": "Быстрое добавление — в одно касание начать новую активность или тег."
          },
          {
            "en": "Navigation — tiles to the sections you use most.",
            "ru": "Навигация — плитки к разделам, которыми вы пользуетесь чаще всего."
          },
          {
            "en": "Rules — the checklist for the current period, a few rules at a time.",
            "ru": "Правила — чек-лист за текущий период, по несколько правил за раз."
          },
          {
            "en": "Metric graph — one metric over time.",
            "ru": "График метрики — одна метрика во времени."
          },
          {
            "en": "Library graph — time spent on an action, tag or item.",
            "ru": "График библиотеки — время на действие, тег или элемент."
          },
          {
            "en": "Experiment — a running experiment at a glance.",
            "ru": "Эксперимент — идущий эксперимент с одного взгляда."
          }
        ]
      }
    ]
  },
  {
    "slug": "backups",
    "title": {
      "en": "Backups",
      "ru": "Резервные копии"
    },
    "summary": {
      "en": "Saving and restoring your whole database, automatically or by hand.",
      "ru": "Сохранение и восстановление всей базы — вручную или автоматически."
    },
    "blocks": [
      {
        "t": "p",
        "text": {
          "en": "A backup is a single encrypted file with your whole database. Make one from Settings → Backup database, and bring it back with Restore database. Files live in Documents/TrackLab/backups.",
          "ru": "Резервная копия — один зашифрованный файл со всей вашей базой. Создайте её через «Настройки → Резервная копия», а верните через «Восстановить». Файлы лежат в Documents/TrackLab/backups."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Automatic backups",
          "ru": "Автоматические копии"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Set a schedule in Settings — daily, weekly or monthly. An automatic backup only runs when you have logged something new since the last one, so unchanged data is never re-saved.",
          "ru": "Задайте расписание в «Настройках» — ежедневно, еженедельно или ежемесячно. Автоматическая копия создаётся, только если вы записали что-то новое с прошлого раза, поэтому неизменные данные не сохраняются заново."
        }
      },
      {
        "t": "h",
        "text": {
          "en": "Passwords and compatibility",
          "ru": "Пароли и совместимость"
        }
      },
      {
        "t": "p",
        "text": {
          "en": "Set a backup password to encrypt your file with your own key; without one it still saves, just without that key. Restore asks for the password only when it needs it. Backups from older versions stay fully compatible — TrackLab migrates them on restore.",
          "ru": "Задайте пароль, чтобы зашифровать файл своим ключом; без него копия всё равно сохранится, просто без этого ключа. При восстановлении пароль спрашивается только тогда, когда нужен. Копии старых версий полностью совместимы — TrackLab переносит их при восстановлении."
        }
      }
    ]
  }
];
